# Generated by Django 4.2.7 on 2023-11-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_room_images'),
        ),
    ]
