# Generated by Django 4.2.7 on 2023-11-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotelroomimage_hotelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
    ]
