# Generated by Django 4.2.7 on 2023-11-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_remove_hotel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='image',
        ),
    ]
