# Generated by Django 4.2.7 on 2023-11-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hotels.hotelroom'),
        ),
    ]
