# Generated by Django 4.2.7 on 2023-11-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_hotel_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='hotels.amenity'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location_type',
            field=models.CharField(choices=[('UR', 'Urban'), ('AP', 'Airport'), ('RE', 'Resort'), ('BF', 'Beachfront'), ('BO', 'Boutique'), ('EC', 'Eco'), ('HW', 'Highway'), ('CA', 'Casino')], default='UR', max_length=2),
        ),
    ]
