# Generated by Django 4.2.7 on 2023-11-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_hotel_location_alter_hotel_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(choices=[('ST', 'Standard'), ('DX', 'Deluxe'), ('SU', 'Suit'), ('FR', 'Family')], default='ST', max_length=2),
        ),
    ]
