# Generated by Django 4.2.7 on 2023-11-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_hotelroom_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location_type',
            field=models.CharField(choices=[('UR', 'Urban'), ('AP', 'Airport'), ('RE', 'Resort'), ('MT', 'Mountain'), ('BF', 'Beachfront'), ('BO', 'Boutique'), ('EC', 'Eco'), ('HW', 'Highway'), ('CA', 'Casino')], default='UR', max_length=2),
        ),
    ]
